### ISSUE TITLE
This app is not compiling

### ISSUE THREAD

**Issue by dimon222** [uvdesk/mobile_app#5]
Below dependency is archived and is no longer compatible to flutter beginning flutter 3.22
`easy_search_bar: ^2.5.0`
It leads to this app not being compiliable as pubspec doesn't set upper lock to lower version of Flutter instead of 4.0.0

**Comment by AnchitAndroidWorld** [comment]
@dimon222 : Currently this project is under code upgradation and we will update to the latest version in near future.
For the reported issue you can do one thing as of now.

Replace the 
easy_search_bar: ^2.5.0

with 
flutter_easy_search_bar: ^0.0.2

And the issue that you reported will be solved.

Reference -> https://pub.dev/packages/flutter_easy_search_bar

Let me know if you face any other issue
